name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      # Only installing chromium to match the test script we are running
      run: npx playwright install --with-deps chromium

    - name: Create .env.chromium file
      run: |
        echo "BROWSER=chromium" >> .env.chromium
        echo "WEB_URL=https://automationexercise.com" >> .env.chromium
        echo "HEADLESS=true" >> .env.chromium
        echo "TEST_USER_EMAIL=${{ secrets.TEST_USER_EMAIL }}" >> .env.chromium
        echo "TEST_USER_PASSWORD=${{ secrets.TEST_USER_PASSWORD }}" >> .env.chromium
      
    - name: Run Playwright tests
      run: npm run test:all

    - name: Generate HTML Report
      if: always() # Ensures the report is generated even if the tests fail
      run: npm run report:generate
      
    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: reports/html-chromium/
        retention-days: 30

    - name: Deploy Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: reports/html-chromium/
        keep_files: true

    - name: Zip the HTML report
      if: always()
      run: zip -r playwright-report.zip reports/html-chromium/

    - name: Send Email with Report
      uses: dawidd6/action-send-mail@v3
      if: always()
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Automation Test Results (${{ job.status }})
        to: sayuzshikhrakar@gmail.com,sayuz6819@gmail.com
        from: GitHub Actions
        body: "The Playwright test run has completed with status - ${{ job.status }}. You can view the full interactive dashboard here: https://sayuzshikhrakar.github.io/AutomationExcercise/"
